version: "3.1"
services:
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: sportradar-mysql
        working_dir: /application
        volumes:
            - ./api:/application
            - ./docker/entryfiles/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=sportradar
            - MYSQL_DATABASE=sportradar
            - MYSQL_USER=sportradar
            - MYSQL_PASSWORD=sportradar
        ports:
            - "3306:3306"

    webserver:
        image: nginx:alpine
        container_name: sportradar-webserver
        working_dir: /application
        volumes:
            - ./api:/application
            - ./docker/nginx/nginx-api.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php-fpm:
        build: docker/php-fpm
        container_name: sportradar-php-fpm
        working_dir: /application
        volumes:
            - ./api:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    client:
        image: nginx:alpine
        container_name: sportradar-client
        working_dir: /var/www/client
        volumes:
            - ./client:/var/www/client
            - ./docker/nginx/nginx-client.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "3000:80"
